<?php View::content(); ?>



      <div id="content">
        <div class="breadcrumbs"> 
        <?php echo Html::link('principal','Estás en: Inicio.');?> » <?php echo Html::link('nosotros','¿Quienes Somos?');?> » Que es Incubem / Historia
       </div>
       
        <h1>INCUBEM-UPeU</h1>
        
        <div class="post_content hyphenate">
          <p><strong>INCUBEM</strong> La incubadora de empresas de la universidad Peruana Unión INCUBEM-UPeU. Es un programa que promueve y brinda y herramientas que permitan optimizar los procesos de gestión de las Pymes, forjando el emprendedorismo y la creación de empresas.
          </p>
          <p>El avance de la Ciencia y la Tecnología se produce de manera constante y más intensa, representa un permanente desafío para toda institución universitaria; especialmente en este siglo, cuando el capital del conocimiento se ha convertido en un eje fundamental para el progreso de un país.</p>
     
          <p>
          Por esto, Incubem persigue como objetivo apoyar a los alumnos:
          </p>
          <p>
          La facultad de Ciencias Empresariales está orientada hacia la preparación de profesionales altamente capacitados, con cultura humanística, valores y criterios de permanente actualización y capacitación. Forma estudiantes mediante normas éticas y principios cristianos.	          </p>
          <p>
          Esta oficina viene prestando sus servicios desde el año 2002, promovemos y brindamos servicios y herramientas que permitan optimizar los procesos de gestión y la mejora de la efectividad de las Pymes, forjando el emprendedorismo y la creación de empresas.
          </p>
          
          <p></p>
          
          </div>
          
      </div>
      
      
      
