<?php View::content(); ?>



      <div id="content">
        <div class="breadcrumbs"> 
        <?php echo Html::link('principal','Estás en: Inicio.');?> » <?php echo Html::link('nosotros/misionvision','Misión / Visión');?> » Que es Incubem / Misión y Visión
       </div>
       
                 
          <h1>Misión / Visión </h1>
          
          <div class="post_content hyphenate">
          
          <p><strong>MI­SIÓN</strong><br> 
          
          Somos una Unidad Operativa de la <strong>Facultad de Ciencias Empresariales de la UPeU</strong>, dedicada al fomento, crecimiento y desarrollo de emprendimientos empresariales con carácter innovador, mediante la pre incubación, incubación y post incubación de empresas, en concordancia con los <strong>principios ético-cristianos</strong> de la <strong>IASD</strong>.
          </p>
          
          <p><strong>MISIÓN</strong><br> 
          
         Ser un Centro de crecimiento y desarrollo del emprendedor, líder en la formación y consolidación de empresas autogestionarios con carácter innovador, altos valores, y espíritu de <strong>servicio a Dios</strong> y a la comunidad.
         </p>
         
          <p><strong>COLABORADORES</strong><br> 
          La Oficina de <strong>INCUBEM</strong> de la <strong>Facultad de Ciencias Empresariales</strong>, de la Universidad Peruana Unión esta debidamente representada por su <strong>Director Lic. Alcides Flores Saenz</strong>.
          </p>
          
      </div>
      </div>
      
      
      
