<div id="real_footer_wrapper">
    <footer> <img class="techo_logo" src="http://www.techo.org/wp-content/themes/techo/images/logo_techo_footer.png" alt="Techo">
      <div class="info">
        <h2>Oficina Central:</h2>
        <ul>
          <li><img src="http://www.techo.org/wp-content/themes/techo/images/icon_location.png" alt="">Departamental #440, San Joaquín, Santiago, Chile.</li>
          <li><img src="http://www.techo.org/wp-content/themes/techo/images/icon_phonenumber.png" alt="">Teléfono: (56) (2) 838 73 00.</li>
          <li><img src="http://www.techo.org/wp-content/themes/techo/images/icon_mail.png" alt="">Email: <a href="mailto:info@techo.org">info@techo.org</a></li>
        </ul>
      </div>
      <a href="http://www.duplika.com" id="duplika" title="Hosting por Duplika"> <img src="http://www.techo.org/wp-content/themes/techo/images/duplika-hosting.png" alt="Duplika"> </a> <a href="http://www.digitalmeat.cl" id="meat" title="Diseñado y desarrollado por MEAT"> <img src="http://www.techo.org/wp-content/themes/techo/images/meat.png" alt="MEAT"> </a> </footer>
  </div>
  