<div class="wrapper header_wrapper">
  <header>
    <div class="top_bar">
      <div class="date right"> <?php echo DwHtml::button("sistema/login/entrar/", 'Ingresar', array('class'=>'btn-success'), 'signin', FALSE); ?> </div>
    </div>
    <?php echo Html::link('#',Html::img('ico-incub3m.png'),array('class'=>'logo'));?>
    <ul class="tools">
      <li>
        <style type="text/css">
header
.tools{overflow:visible}.global_countries_menu
ul{display:none;background:white;text-align:left;font-size:12px;border:solid 1px #F6F6F6;border-radius:5px;box-shadow:0px 7px 7px rgba(0, 0, 0, 0.2);position:absolute;top:27px;left:0px;z-index:100;padding:5px}.global_countries_menu
li{text-align:left;float:none !important;background:none;margin:0;display:block;white-space:nowrap;overflow:hidden;border-bottom:dotted 1px gainsboro;padding:5px}.global_countries_menu:hover
ul{display:block}
</style>
        <div class="global_countries_menu"> <a class="button" href="http://www.techo.org/techo/paises">Países »</a>
          <ul>
            <li><a href="http://www.untechoparamipais.org/argentina">Argentina</a></li>
            <li><a href="http://www.techo.org/bolivia">Bolivia</a></li>
            <li><a href="http://teto.org.br/">Brasil</a></li>
            <li><a href="http://www.untechoparachile.cl/">Chile</a></li>
            <li><a href="http://www.techo.org/costarica">Costa Rica</a></li>
            <li><a href="http://www.untechoparamipais.org/colombia">Colombia</a></li>
            <li><a href="http://www.untechoparamipais.org/ecuador">Ecuador</a></li>
            <li><a href="http://www.untechoparamipais.org/elsalvador">El Salvador</a></li>
            <li><a href="http://www.techo.org/guatemala">Guatemala</a></li>
            <li><a href="http://www.techo.org/haiti">Haití</a></li>
            <li><a href="http://www.techo.org/honduras">Honduras</a></li>
            <li><a href="http://www.techo.org/mexico">México</a></li>
            <li><a href="http://www.techo.org/nicaragua">Nicaragua</a></li>
            <li><a href="http://www.untechoparamipais.org/paraguay">Paraguay</a></li>
            <li><a href="http://www.untechoparamipais.org/panama">Panamá</a></li>
            <li><a href="http://www.techo.org/peru">Perú</a></li>
            <li><a href="http://www.techo.org/republicadominicana">República Dominicana</a></li>
            <li><a href="http://www.techo.org/uruguay/">Uruguay</a></li>
            <li><a href="http://www.techo.org/us/">USA</a></li>
            <li><a href="http://www.techo.org/venezuela">Venezuela</a></li>
          </ul>
        </div>
      </li>
      <li><a class="button" href="http://www.techo.org/en/">English version »</a></li>
      <li class="social"><a href="https://www.facebook.com/incubem" target="_blank" title="Ir a la página de Incubem en Facebook" class="facebook"></a></li>
      <li class="social"><a href="#" target="_blank" title="Ir a la página de Incubem en Twitter" class="twitter"></a></li>
      <li class="social"><a href="#" target="_blank" title="Ir a la página de Incubem en Flickr" class="flickr"></a></li>
      <li class="social"><a href="#" target="_blank" title="Ir a la página de Incubem en YouTube" class="youtube"></a></li>
      <li class="social"><a href="http://www.linkedin.com/company/306939?trk=tyah" target="_blank" title="Ir a la página de Techo en LinkedIn" class="linkedin"></a></li>
      <li class="social"><a href="#" target="_blank" title="Ir a la página de Incubem en Google Plus" class="googleplus"></a></li>
      <li class="social"><a href="#" target="_blank" title="Ir a la página de Incubem en Pinterest" class="pinterest"></a></li>
      <li class="social"><a href="#" target="_blank" title="Ir a la página de Incubem en Instagram" class="instagram"></a></li>
      <li class="searchbox">
        <form action="" method="get" class="search-site">
          <input type="text" name="s" id="keywords" value="¿Qué estás buscando?">
        </form>
      </li>
    </ul>
    <nav>
      <ul>
        <li class="active"><?php echo Html::link('principal','Inicio');?> </li>
        <li class="active"> <?php echo Html::link('nosotros','¿Quienes Somos?');?>
        <ul>
            <li>
			<?php echo Html::link('nosotros/misionvision','Misión / Visión');?>
            </li>
            </ul>
        </li>
        <li class="active"> <?php echo Html::link('servicios','Servicios');?>
   
        <li class="active"> <?php echo Html::link('emprendedores','Incubados');?>
        </li>
         <!-- <ul>
            <li><a href="http://www.techo.org/comunicados-de-prensa/">Comunicados de prensa</a></li>
            <li class="page_item page-item-90"><a href="http://www.techo.org/sala-de-prensa/actividades-techo/">Actividades TECHO</a></li>
            <li class="page_item page-item-82"><a href="http://www.techo.org/sala-de-prensa/audiovisual/">Audiovisual</a></li>
            <li class="page_item page-item-92"><a href="http://www.techo.org/sala-de-prensa/contactos/">Contactos</a></li>
            <li class="page_item page-item-88"><a href="http://www.techo.org/sala-de-prensa/material-institucional/">Material institucional</a></li>
          </ul>-->
        
        <li class="last "> <li class="active"> <?php echo Html::link('contacto','Formulario');?> </a></li>
      </ul>
    </nav>
  </header>
</div>
