<div id="sidebar">
        <div class="latest_posts">
          <h4>INCUBEM</h4>
          <ul>
            <li class="page_item page-item-150 current_page_item"><a href="http://www.techo.org/techo/que-es-techo/">Qué es TECHO / Historia</a></li>
            <li class="page_item page-item-69"><a href="http://www.techo.org/techo/mision-vision-valores/">Misión / Visión – Valores</a></li>
            <li class="page_item page-item-71"><a href="http://www.techo.org/techo/modelo-de-trabajo-techo/">Modelo de trabajo TECHO</a></li>
            <li class="page_item page-item-75"><a href="http://www.techo.org/techo/transparencia/">Transparencia</a></li>
            <li class="page_item page-item-1370"><a href="http://www.techo.org/techo/cis/">Centro de Investigación Social</a></li>
            <li class="page_item page-item-829"><a href="http://www.techo.org/techo/postulaciones/">Postulaciones</a></li>
            <li class="page_item page-item-80"><a href="http://www.techo.org/techo/preguntas-frecuentes/">Preguntas frecuentes</a></li>
            <li class="page_item page-item-1083"><a href="http://www.techo.org/techo/premios-y-reconocimientos/">Premios y reconocimientos</a></li>
          </ul>
        </div>
        <div class="latest_posts">
          <h4>Últimas noticias</h4>
          <ul>
            <li>
              <div class="date">19 abril, 2014</div>
              <a href="http://www.techo.org/informate/viviendo-con-un-dolar-al-dia/">Viviendo con un dólar al día, ¿qué dices?</a></li>
            <li>
              <div class="date">18 abril, 2014</div>
              <a href="http://www.techo.org/informate/tecnologia-servicio-de-la-sociedad/">Tecnología al servicio de la sociedad</a></li>
            <li>
              <div class="date">18 abril, 2014</div>
              <a href="http://www.techo.org/informate/2-000-damnificados-por-el-incendio-de-valparaiso-vienen-de-asentamientos-informales/">2.000 damnificados por el incendio de Valparaíso vienen de Asentamientos Informales</a></li>
            <li>
              <div class="date">14 abril, 2014</div>
              <a href="http://www.techo.org/informate/emergencia-valparaiso/">TECHO-Chile se moviliza para trabajar junto a los 10.000 daminificados del incendio en Valparaíso</a></li>
          </ul>
        </div>
        <div class="newsletter">
          <h4>Newsletter</h4>
          <form action="http://alpha.emailpanel.net/proc.php" method="post" id="_form_26788" accept-charset="utf-8" enctype="multipart/form-data" style="margin-bottom:3;">
            <input type="text" name="email" id="ea" value="Ingresa tu correo para recibir noticias">
            <input type="hidden" name="f" value="26788">
            <input type="hidden" name="s" value="">
            <input type="hidden" name="c" value="0">
            <input type="hidden" name="m" value="0">
            <input type="hidden" name="act" value="sub">
            <input type="hidden" name="nlbox[]" value="3743">
            <input type="submit" value="Enviar">
          </form>
        </div>
        <div class="social">
          <div class="social">
            <div class="fb-like-box fb_iframe_widget" data-href="https://www.facebook.com/incubem" data-width="260" data-height="200" data-show-faces="true" data-stream="false" data-header="true" fb-xfbml-state="rendered" fb-iframe-plugin-query="app_id=231267446987161&amp;header=true&amp;height=200&amp;href=https%3A%2F%2Fwww.facebook.com%2Fpages%2FTecho%2F79616214317&amp;locale=es_ES&amp;sdk=joey&amp;show_faces=true&amp;stream=false&amp;width=260"><span style="vertical-align: bottom; width: 260px; height: 200px;">
              <iframe name="f29c4678a" width="260px" height="200px" frameborder="0" allowtransparency="true" scrolling="no" title="fb:like_box Facebook Social Plugin" src="http://www.facebook.com/plugins/like_box.php?app_id=231267446987161&amp;channel=http%3A%2F%2Fstatic.ak.facebook.com%2Fconnect%2Fxd_arbiter%2FdgdTycPTSRj.js%3Fversion%3D40%23cb%3Dfe30e40f4%26domain%3Dwww.techo.org%26origin%3Dhttp%253A%252F%252Fwww.techo.org%252Ff3abee876c%26relation%3Dparent.parent&amp;header=true&amp;height=200&amp;href=https%3A%2F%2Fwww.facebook.com%2Fpages%2FTecho%2F79616214317&amp;locale=es_ES&amp;sdk=joey&amp;show_faces=true&amp;stream=false&amp;width=260" class="" style="border: none; visibility: visible; width: 260px; height: 200px;"></iframe>
              </span></div>
            <script charset="utf-8" src="http://widgets.twimg.com/j/2/widget.js"></script><script>
	new TWTR.Widget({
	  version: 2,
	  type: 'profile',
	  rpp: 1,
	  interval: 30000,
	  width: 260,
	  height: 300,
	  theme: {
		shell: {
		  background: '#d9d9d9',
		  color: '#2d7fc6'
		},
		tweets: {
		  background: '#ffffff',
		  color: '#8e9aa9',
		  links: '#2d7fc6'
		}
	  },
	  features: {
		scrollbar: false,
		loop: false,
		live: false,
		behavior: 'all'
	  }
	}).render().setUser('untecho').start();
	</script></div>
        </div>
      </div>