<?php View::content(); ?>

<div id="content">
  <div class="breadcrumbs"> 
        <?php echo Html::link('principal','Estás en: Inicio.');?> » 
		<?php echo Html::link('servicios','Servicios.');?> » Servicios.
       </div>
       
  <h1>Servicios</h1>
  
  <div class="post_content hyphenate">
    <p><strong>Talleres</strong></p>
    
    <p>
    Talleres de emprendimiento, que tienen como finalidad formar emprendedores, realizar y dar ejecucion a ideas de negocio  para estudiantes  de la <strong>Universidad Peruana Union</strong> y publico en general, y asi  formar una gama de empresarios.
    </p>
    
    <p style="text-align: center;"><a href="http://www.flickr.com/photos/untechoparamipais/sets/72157631794025074/">
    
    <?php echo Html::img('logoexpo.jpg','', array('class'=>'aligncenter  wp-image-1254','title'=>'avatar_500x500', 'width'=>'300', 'height'=>'300')); ?>
     
    
    </p>
    
    <p><strong id="internal-source-marker_0.3309874644037336">Video ins­ti­tu­cio­nal 2012</strong></p>
    <p>
      <iframe src="http://www.youtube.com/embed/Ownint18mEo" frameborder="0" width="560" height="315"></iframe>
    </p>
    <p><strong id="internal-source-marker_0.3309874644037336">Video cam­bio ins­ti­tu­cio­nal 2012</strong></p>
    <p><strong id="internal-source-marker_0.3309874644037336"><br>
      </strong>Luego de una serie de cam­bios in­ter­nos, donde la or­ga­ni­za­ción pasó de una etapa fun­da­cio­nal a una de con­so­li­da­ción, hoy somos TECHO y en este video te ex­pli­ca­mos por qué:</p>
    <p>
      <iframe src="http://www.youtube.com/embed/QlPyunEHqdI" frameborder="0" width="560" height="315"></iframe>
    </p>
    <p><strong>En­cuen­tro La­ti­noa­me­ri­cano de Lí­de­res Co­mu­ni­ta­rios</strong></p>
    <p><strong></strong>Desde el 3 al 6 de oc­tu­bre del 2011 se reali­zó el 1er En­cuen­tro La­ti­noa­me­ri­cano de Lí­de­res Co­mu­ni­ta­rios, que reunió en Perú a más de 100 lí­de­res de de Costa Rica, Ar­gen­ti­na, Uru­guay, Mé­xi­co, Bo­li­via, Chile, Co­lom­bia, Haití, El Sal­va­dor y Perú.<br>
      Este video re­su­me el pri­mer día de jor­na­da:</p>
    <p>
      <iframe src="http://www.youtube.com/embed/jnJh7TpRfTg" frameborder="0" width="560" height="315"></iframe>
    </p>
  </div>
</div>