<?php View::content(); ?>


<div class="wrapper body_wrapper">
  <section class="body single page">
    <div class="content_wrapper">
      <div id="content">
        <div class="breadcrumbs"> <a title="Go to Estás en: Inicio." href="http://www.techo.org">Estás en: Inicio</a> » <a title="Go to TECHO." href="#n">TECHO</a> » Qué es TECHO / Historia</div>
        <h1>Qué es TECHO / Historia</h1>
        <div class="post_content hyphenate">
          <p><strong>TECHO</strong> es una or­ga­ni­za­ción pre­sen­te en La­ti­noa­mé­ri­ca y El Ca­ri­be que busca su­perar la si­tua­ción de po­bre­za que viven miles de per­so­nas en los asen­ta­mien­tos pre­ca­rios, a tra­vés de la ac­ción con­jun­ta de sus po­bla­do­res y jó­ve­nes vo­lun­ta­rios.</p>
          <p><strong>TECHO</strong> tiene la con­vic­ción de que la po­bre­za se puede su­perar de­fi­ni­ti­va­men­te si la so­cie­dad en su con­jun­to logra re­co­no­cer que éste es un pro­ble­ma prio­ri­ta­rio y tra­ba­ja ac­ti­va­men­te por re­sol­ver­lo.</p>
          <p>
            <iframe src="https://www.youtube.com/watch?v=Yr1cYR6B8gU" frameborder="0" width="560" height="315"></iframe>
          </p>
          <p>Por esto, TECHO per­si­gue tres ob­je­ti­vos es­tra­té­gi­cos:</p>
          <p><strong>(1) Fo­men­tar el desa­rro­llo co­mu­ni­ta­rio en asen­ta­mien­tos pre­ca­rios,</strong> a tra­vés de un pro­ce­so de for­ta­le­ci­mien­to de la co­mu­ni­dad, que desa­rro­lle li­de­raz­gos va­li­da­dos y re­pre­sen­ta­ti­vos, y que im­pul­se la or­ga­ni­za­ción y par­ti­ci­pa­ción de miles de po­bla­do­res de asen­ta­mien­tos para la ge­ne­ra­ción de so­lu­cio­nes a sus pro­ble­má­ti­cas. El desa­rro­llo co­mu­ni­ta­rio es con­si­de­ra­do como eje trans­ver­sal del tra­ba­jo de TECHO en asen­ta­mien­tos pre­ca­rios.</p>
          <p><strong>(2) Pro­mo­ver la con­cien­cia y ac­ción so­cial,</strong> con es­pe­cial én­fa­sis en la ma­si­fi­ca­ción del vo­lun­ta­ria­do crí­ti­co y pro­po­si­ti­vo tra­ba­jan­do en te­rreno con los po­bla­do­res de los asen­ta­mien­tos e in­vo­lu­cran­do a dis­tin­tos ac­to­res de la so­cie­dad en el desa­rro­llo de so­lu­cio­nes con­cre­tas para erra­di­car la po­bre­za.</p>
          <p><strong>(3)&nbsp;In­ci­dir&nbsp;en es­pa­cios de toma de de­ci­sión y de de­fi­ni­ción de po­lí­ti­cas pú­bli­cas</strong> a tra­vés de la de­nun­cia de la ex­clu­sión y vul­ne­ra­ción de de­re­chos den­tro de los asen­ta­mien­tos, de la ge­ne­ra­ción y di­fu­sión de in­for­ma­ción re­le­van­te sobre estos y de la vin­cu­la­ción de sus po­bla­do­res con otras redes. Todo esto para que los pro­ble­mas de estas co­mu­ni­da­des sean re­co­no­ci­dos por la so­cie­dad y prio­ri­ta­rios en la agen­da pú­bli­ca.</p>
          <p><strong>TECHO en ci­fras</strong></p>
          <p><strong>- 89.500 fa­mi­lias de asen­ta­mien­tos</strong> han tra­ba­ja­do en con­jun­to con los vo­lun­ta­rios en la cons­truc­ción de su vi­vien­da.<br>
            <strong>&nbsp;- 530.000 vo­lun­ta­rios</strong> se han mo­vi­li­za­do en Amé­ri­ca La­ti­na por ter­mi­nar con la po­bre­za y la ex­clu­sión.<br>
            <strong>&nbsp;- 880 mesas de tra­ba­jo</strong> im­ple­men­ta­das en asen­ta­mien­tos pre­ca­rios.<br>
            <strong>&nbsp;- 8.600 po­bla­do­res</strong> gra­dua­dos en ofi­cios.<br>
            <strong>&nbsp;- 344 sedes co­mu­ni­ta­rias</strong> cons­trui­das en asen­ta­mien­tos.<br>
            <strong>- 15.000 niños</strong> que viven en asen­ta­mien­tos han par­ti­ci­pa­do en los pro­gra­mas de edu­ca­ción.<br>
            <strong>&nbsp;- 3.310 vi­vien­das de­fi­ni­ti­vas</strong> en­tre­ga­das.</p>
          <p><strong>HIS­TO­RIA</strong></p>
          <p>En&nbsp;<strong>1997</strong>&nbsp;un grupo de jó­ve­nes co­men­zó a tra­ba­jar por el s<strong>ueño de su­perar la si­tua­ción de po­bre­za</strong>&nbsp;en la que vi­vían mi­llo­nes de per­so­nas. El sen­ti­do de ur­gen­cia en los asen­ta­mien­tos los mo­vi­li­zó ma­si­va­men­te a&nbsp;<strong>cons­truir</strong>&nbsp;<strong>vi­vien­das de emer­gen­cia en con­jun­to con las fa­mi­lias</strong>&nbsp;que vi­vían en con­di­cio­nes inacep­ta­bles y a vol­car su ener­gía en busca de so­lu­cio­nes con­cre­tas a las pro­ble­má­ti­cas que las co­mu­ni­da­des afron­ta­ban cada día.</p>
          <p>Esta ini­cia­ti­va se con­vir­tió en un&nbsp;<strong>desa­fío ins­ti­tu­cio­nal</strong>&nbsp;que hoy se com­par­te en todo el con­ti­nen­te. Desde sus inicios en Chile, se­gui­do por El Sal­va­dor y Perú, la or­ga­ni­za­ción em­pren­dió su ex­pan­sión bajo el nom­bre "Un Techo para mi País".</p>
          <p>Luego de 15 años de tra­ba­jo, TECHO man­tie­ne&nbsp;<strong>ope­ra­ción en 19 paí­ses de La­ti­noa­mé­ri­ca y el Ca­ri­be:</strong>&nbsp;Ar­gen­ti­na, Bo­li­via, Bra­sil, Chile, Co­lom­bia, Costa Rica, Ecua­dor, El Sal­va­dor, Gua­te­ma­la, Haití, Hon­du­ras, Mé­xi­co, Ni­ca­ra­gua, Pa­na­má, Pa­ra­guay, Perú, Re­pú­bli­ca Do­mi­ni­ca­na, Uru­guay y Ve­ne­zue­la. Ade­más, cuen­ta con una ofi­ci­na en Es­ta­dos Uni­dos.</p>
        </div>
      </div>
      <div id="sidebar">
        <div class="latest_posts">
          <h4>TECHO</h4>
          <ul>
            <li class="page_item page-item-150 current_page_item"><a href="http://www.techo.org/techo/que-es-techo/">Qué es TECHO / Historia</a></li>
            <li class="page_item page-item-69"><a href="http://www.techo.org/techo/mision-vision-valores/">Misión / Visión – Valores</a></li>
            <li class="page_item page-item-71"><a href="http://www.techo.org/techo/modelo-de-trabajo-techo/">Modelo de trabajo TECHO</a></li>
            <li class="page_item page-item-75"><a href="http://www.techo.org/techo/transparencia/">Transparencia</a></li>
            <li class="page_item page-item-1370"><a href="http://www.techo.org/techo/cis/">Centro de Investigación Social</a></li>
            <li class="page_item page-item-829"><a href="http://www.techo.org/techo/postulaciones/">Postulaciones</a></li>
            <li class="page_item page-item-80"><a href="http://www.techo.org/techo/preguntas-frecuentes/">Preguntas frecuentes</a></li>
            <li class="page_item page-item-1083"><a href="http://www.techo.org/techo/premios-y-reconocimientos/">Premios y reconocimientos</a></li>
          </ul>
        </div>
        <div class="latest_posts">
          <h4>Últimas noticias</h4>
          <ul>
            <li>
              <div class="date">19 abril, 2014</div>
              <a href="http://www.techo.org/informate/viviendo-con-un-dolar-al-dia/">Viviendo con un dólar al día, ¿qué dices?</a></li>
            <li>
              <div class="date">18 abril, 2014</div>
              <a href="http://www.techo.org/informate/tecnologia-servicio-de-la-sociedad/">Tecnología al servicio de la sociedad</a></li>
            <li>
              <div class="date">18 abril, 2014</div>
              <a href="http://www.techo.org/informate/2-000-damnificados-por-el-incendio-de-valparaiso-vienen-de-asentamientos-informales/">2.000 damnificados por el incendio de Valparaíso vienen de Asentamientos Informales</a></li>
            <li>
              <div class="date">14 abril, 2014</div>
              <a href="http://www.techo.org/informate/emergencia-valparaiso/">TECHO-Chile se moviliza para trabajar junto a los 10.000 daminificados del incendio en Valparaíso</a></li>
          </ul>
        </div>
        <div class="newsletter">
          <h4>Newsletter</h4>
          <form action="http://alpha.emailpanel.net/proc.php" method="post" id="_form_26788" accept-charset="utf-8" enctype="multipart/form-data" style="margin-bottom:3;">
            <input type="text" name="email" id="ea" value="Ingresa tu correo para recibir noticias">
            <input type="hidden" name="f" value="26788">
            <input type="hidden" name="s" value="">
            <input type="hidden" name="c" value="0">
            <input type="hidden" name="m" value="0">
            <input type="hidden" name="act" value="sub">
            <input type="hidden" name="nlbox[]" value="3743">
            <input type="submit" value="Enviar">
          </form>
        </div>
        <div class="social">
          <div class="social">
            <div class="fb-like-box fb_iframe_widget" data-href="https://www.facebook.com/pages/Techo/79616214317" data-width="260" data-height="200" data-show-faces="true" data-stream="false" data-header="true" fb-xfbml-state="rendered" fb-iframe-plugin-query="app_id=231267446987161&amp;header=true&amp;height=200&amp;href=https%3A%2F%2Fwww.facebook.com%2Fpages%2FTecho%2F79616214317&amp;locale=es_ES&amp;sdk=joey&amp;show_faces=true&amp;stream=false&amp;width=260"><span style="vertical-align: bottom; width: 260px; height: 200px;">
              <iframe name="f29c4678a" width="260px" height="200px" frameborder="0" allowtransparency="true" scrolling="no" title="fb:like_box Facebook Social Plugin" src="http://www.facebook.com/plugins/like_box.php?app_id=231267446987161&amp;channel=http%3A%2F%2Fstatic.ak.facebook.com%2Fconnect%2Fxd_arbiter%2FdgdTycPTSRj.js%3Fversion%3D40%23cb%3Dfe30e40f4%26domain%3Dwww.techo.org%26origin%3Dhttp%253A%252F%252Fwww.techo.org%252Ff3abee876c%26relation%3Dparent.parent&amp;header=true&amp;height=200&amp;href=https%3A%2F%2Fwww.facebook.com%2Fpages%2FTecho%2F79616214317&amp;locale=es_ES&amp;sdk=joey&amp;show_faces=true&amp;stream=false&amp;width=260" class="" style="border: none; visibility: visible; width: 260px; height: 200px;"></iframe>
              </span></div>
            <script charset="utf-8" src="http://widgets.twimg.com/j/2/widget.js"></script><script>
	new TWTR.Widget({
	  version: 2,
	  type: 'profile',
	  rpp: 1,
	  interval: 30000,
	  width: 260,
	  height: 300,
	  theme: {
		shell: {
		  background: '#d9d9d9',
		  color: '#2d7fc6'
		},
		tweets: {
		  background: '#ffffff',
		  color: '#8e9aa9',
		  links: '#2d7fc6'
		}
	  },
	  features: {
		scrollbar: false,
		loop: false,
		live: false,
		behavior: 'all'
	  }
	}).render().setUser('untecho').start();
	</script></div>
        </div>
      </div>
    </div>
  </section>
</div>