<?php View::content(); ?>

      <div id="content">
        <div class="breadcrumbs"> <a title="Go to Estás en: Inicio." href="http://www.techo.org">Estás en: Inicio</a> » Formulario de contacto</div>
        <h1>Formulario de contacto</h1>
        <div class="post_content hyphenate">
          <p>Tu for­mu­la­rio será re­cep­cio­na­do por el box de in­for­ma­ción de la Ofi­ci­na Cen­tral de TECHO, que coor­di­na el tra­ba­jo que rea­li­za­mos en los 19 paí­ses de La­ti­noa­mé­ri­ca en que es­ta­mos pre­sen­tes tra­ba­jan­do junto a vo­lun­ta­rios y po­bla­do­res para su­perar la si­tua­ción de po­bre­za de quie­nes ha­bi­tan en asen­ta­mien­tos, ade­más de las ofi­ci­nas que TECHO lleva en Es­ta­dos Uni­dos.</p>
          <p>Si quie­res es­ta­ble­cer con­tac­to con al­gu­na ofi­ci­na local en par­ti­cu­lar,<a href="http://www.techo.org/contacto-de-informaciones/" target="_blank"> acá </a>en­con­tra­rás el con­tac­to di­rec­to con cada una.</p>
          <p>Para dudas sobre la ins­tit­tu­ción, vo­lun­ta­ria­do y fi­nan­cia­mien­to, pue­des con­sul­tar <a href="http://www.techo.org/techo/preguntas-frecuentes/">acá.</a></p>
          <div class="wpcf7" id="wpcf7-f161-p106-o1">
            <form action="/formulario-de-contacto/#wpcf7-f161-p106-o1" method="post" class="wpcf7-form">
              <div style="display: none;">
                <input type="hidden" name="_wpcf7" value="161">
                <input type="hidden" name="_wpcf7_version" value="3.1.2">
                <input type="hidden" name="_wpcf7_unit_tag" value="wpcf7-f161-p106-o1">
                <input type="hidden" name="_wpnonce" value="96e671b3e2">
              </div>
              <p>Tu nom­bre (re­que­ri­do)<br>
                <span class="wpcf7-form-control-wrap your-name">
                <input type="text" name="your-name" value="" class="wpcf7-form-control wpcf7-text wpcf7-validates-as-required" size="40">
                </span></p>
              <p>Tu Email (re­que­ri­do)<br>
                <span class="wpcf7-form-control-wrap your-email">
                <input type="text" name="your-email" value="" class="wpcf7-form-control wpcf7-text wpcf7-email wpcf7-validates-as-required wpcf7-validates-as-email" size="40">
                </span></p>
              <p>País desde donde nos es­cri­bes<br>
                <span class="wpcf7-form-control-wrap Pais">
                <input type="text" name="Pais" value="" class="wpcf7-form-control wpcf7-text wpcf7-validates-as-required" size="40">
                </span></p>
              <p>Ofi­ci­na Local del País al que desea con­tac­tar<br>
                <span class="wpcf7-form-control-wrap contact-office">
                <select name="contact-office" class="wpcf7-form-control  wpcf7-select wpcf7-validates-as-required">
                  <option value="">---</option>
                  <option value="Oficina Central">Oficina Central</option>
                  <option value="Argentina">Argentina</option>
                  <option value="Bolivia">Bolivia</option>
                  <option value="Brasil">Brasil</option>
                  <option value="Chile">Chile</option>
                  <option value="Colombia">Colombia</option>
                  <option value="Costa Rica">Costa Rica</option>
                  <option value="Ecuador">Ecuador</option>
                  <option value="El Salvador">El Salvador</option>
                  <option value="Estados Unidos">Estados Unidos</option>
                  <option value="Guatemala">Guatemala</option>
                  <option value="Haiti">Haiti</option>
                  <option value="Honduras">Honduras</option>
                  <option value="Mexico">Mexico</option>
                  <option value="Nicaragua">Nicaragua</option>
                  <option value="Panama">Panama</option>
                  <option value="Paraguay">Paraguay</option>
                  <option value="Peru">Peru</option>
                  <option value="Republica Dominicaca">Republica Dominicaca</option>
                  <option value="Uruguay">Uruguay</option>
                  <option value="Venezuela">Venezuela</option>
                </select>
                </span></p>
              <p>Asun­to<br>
                <br>
                <span class="wpcf7-form-control-wrap your-subject">
                <input type="text" name="your-subject" value="" class="wpcf7-form-control wpcf7-text" size="40">
                </span></p>
              <p>Tu Men­sa­je<br>
                <span class="wpcf7-form-control-wrap your-message">
                <textarea name="your-message" class="wpcf7-form-control  wpcf7-textarea" cols="40" rows="10"></textarea>
                </span></p>
              <p>
                <input type="submit" value="Enviar" class="wpcf7-form-control  wpcf7-submit">
                <img class="ajax-loader" src="http://www.techo.org/wp-content/plugins/contact-form-7/images/ajax-loader.gif" alt="Enviando..." style="visibility: hidden;"></p>
              <div class="wpcf7-response-output wpcf7-display-none"></div>
            </form>
          </div>
        </div>
      </div>
      
