<?php View::content(); ?>

<div class="content-postulacion">
  <div class="breadcrumbs"> <a title="Go to Estás en: Inicio." href="http://www.techo.org">Estás en: Inicio</a> » <a title="Go to TECHO." href="#n">TECHO</a> » Postulaciones</div>
  <h1>Postulaciones</h1>
  <div class="post_content hyphenate">
    <p>
      <iframe id="_theFrame" style="display: block; background-image: none; background-attachment: scroll; background-color: transparent; width: 100%; background-position: 0% 0%; background-repeat: repeat repeat;" src="./emprendedores/iframe" frameborder="0" marginwidth="0" marginheight="0" width="100%" height="800"></iframe>
    </p>
  </div>